# -*- coding: utf-8 -*-
"""small_IDS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yu8b1wujLd7gy-29kcWoU2-_lAeEApjs
"""

import pandas as pd

data = {
    "Src Port": [80, 53, 22, 443, 21, 53, 80, 443],
    "Dst Port": [443, 1024, 5000, 80, 5001, 2048, 3000, 8000],
    "Protocol": ["TCP", "UDP", "TCP", "TCP", "TCP", "UDP", "TCP", "TCP"],
    "Packet Size": [500, 100, 800, 450, 1200, 90, 950, 600],
    "Attack Type": ["Normal", "Normal", "Attack", "Normal", "Attack", "Normal", "Attack", "Normal"]
}

df = pd.DataFrame(data)

print(df)

from sklearn.preprocessing import LabelEncoder
protocol_encoder = LabelEncoder()
df["Protocol"] = protocol_encoder.fit_transform(df["Protocol"])

df

attackType_encoder = LabelEncoder()
df["Attack Type"] = attackType_encoder.fit_transform(df["Attack Type"])

df

from sklearn.model_selection import train_test_split
x = df.drop(columns=["Attack Type"])
y = df["Attack Type"]

x

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

print(f"Training samples: {len(x_train)}\nTesting samples: {len(x_test)}")

from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(x_train, y_train)
print('Model trainig completed!')

y_predict = model.predict(x_test)
print('Predictions: ',y_predict.tolist())
print('Actual results: ',y_test.tolist())

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_predict)
print(f'Model accuracy: {(accuracy*100):.2f}')

